### ISSUE TITLE
URLComposer providing wrong value.

### ISSUE THREAD

**Issue by somnand** [somnand/BingpaperDownloader#2]
g_img={url: searching for the next to next token after this yields a wrong image URL to be downloaded.

**Comment by somnand** [comment]
User logs generated for the failure.
F:\Virtual Storage(DO NOT DELETE)>java -jar BingpaperDownloader-0.0.2-SNAPSHOT-jar-with-dependencies.jar
System Error : Unable to download image
Exception in thread "main" java.lang.NullPointerException
        at code.ImageDownloader.download(ImageDownloader.java:55)
        at code.Control.main(Control.java:12)

F:\Virtual Storage(DO NOT DELETE)>java -version
java version "1.6.0_38-ea"
Java(TM) SE Runtime Environment (build 1.6.0_38-ea-b04)
Java HotSpot(TM) Client VM (build 20.13-b02, mixed mode, sharing)

F:\Virtual Storage(DO NOT DELETE)>javac -version
'javac' is not recognized as an internal or external command,
operable program or batch file.

**Comment by somnand** [comment]
Closing issue for URLComposer. Docs added to the classes and functions. Project cleaned and restructured.
